In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../../datasets/Pfizer.csv')
df

,ID,Date,drug_name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,1,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,2,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,3,16-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,4,16-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,5,17-10-2020,erythrocin™ lactobionate,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,6,17-10-2020,erythrocin™ lactobionate,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,7,18-10-2020,fentanyl citrate,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,8,18-10-2020,fentanyl citrate,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,9,19-10-2020,gentamicin sulfate,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,10,19-10-2020,gentamicin sulfate,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,11,20-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,12,20-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,13,21-10-2020,ammonium chloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,14,21-10-2020,ammonium chloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,15,22-10-2020,butorphanol tartrate,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,16,22-10-2020,butorphanol tartrate,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17,23-10-2020,buprenorphine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,18,23-10-2020,buprenorphine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15
18,19,24-10-2020,skelaxin®,Temperature,13.0,13.0,13.0,13.0,13.0,14,13.0,14.0,13.0,12,13.0,13
19,20,24-10-2020,skelaxin®,Pressure,12.0,11.0,11.0,11.0,13.0,14,16.0,16.0,17.0,18,19.0,20

In [4]:
df.isna()

,ID,Date,drug_name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
3,False,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
4,False,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False
5,False,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
11,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
df.isna().sum()

ID           0
Date         0
drug_name    0
Parameter    0
1:30:00      2
2:30:00      2
3:30:00      6
4:30:00      4
5:30:00      2
6:30:00      0
7:30:00      2
8:30:00      4
9:30:00      2
10:30:00     0
11:30:00     2
12:30:00     0
dtype: int64

In [6]:
df.isna().count()

ID           20
Date         20
drug_name    20
Parameter    20
1:30:00      20
2:30:00      20
3:30:00      20
4:30:00      20
5:30:00      20
6:30:00      20
7:30:00      20
8:30:00      20
9:30:00      20
10:30:00     20
11:30:00     20
12:30:00     20
dtype: int64

In [7]:
df.value_counts()

ID  Date        drug_name                    Parameter    1:30:00  2:30:00  3:30:00  4:30:00  5:30:00  6:30:00  7:30:00  8:30:00  9:30:00  10:30:00  11:30:00  12:30:00
15  22-10-2020  butorphanol tartrate         Temperature  12.0     13.0     14.0     15.0     16.0     17       18.0     19.0     20.0     21        22.0      23          1
16  22-10-2020  butorphanol tartrate         Pressure     20.0     22.0     22.0     22.0     22.0     23       25.0     26.0     27.0     28        29.0      28          1
17  23-10-2020  buprenorphine hydrochloride  Temperature  13.0     14.0     15.0     16.0     17.0     18       19.0     20.0     21.0     22        23.0      24          1
18  23-10-2020  buprenorphine hydrochloride  Pressure     8.0      9.0      10.0     11.0     11.0     12       12.0     11.0     12.0     13        14.0      15          1
19  24-10-2020  skelaxin®                    Temperature  13.0     13.0     13.0     13.0     13.0     14       13.0     14.0     13.0     12        13.0      13          1
20  24-10-2020  skelaxin®                    Pressure     12.0     11.0     11.0     11.0     13.0     14       16.0     16.0     17.0     18        19.0      20          1
dtype: int64

In [9]:
pd.melt(df, 
       id_vars=['Date', 'Parameter', 'drug_name'])

           Date    Parameter                    drug_name  variable  value
0    15-10-2020  Temperature      diltiazem hydrochloride        ID    1.0
1    15-10-2020     Pressure      diltiazem hydrochloride        ID    2.0
2    16-10-2020  Temperature          docetaxel injection        ID    3.0
3    16-10-2020     Pressure          docetaxel injection        ID    4.0
4    17-10-2020  Temperature     erythrocin™ lactobionate        ID    5.0
..          ...          ...                          ...       ...    ...
255  22-10-2020     Pressure         butorphanol tartrate  12:30:00   28.0
256  23-10-2020  Temperature  buprenorphine hydrochloride  12:30:00   24.0
257  23-10-2020     Pressure  buprenorphine hydrochloride  12:30:00   15.0
258  24-10-2020  Temperature                    skelaxin®  12:30:00   13.0
259  24-10-2020     Pressure                    skelaxin®  12:30:00   20.0

[260 rows x 5 columns]

In [12]:
melting_data = pd.melt(df, 
       id_vars=['Date', 'Parameter', 'drug_name'],
       var_name="Time",
       value_name="Result")

In [15]:
melting_data

           Date    Parameter                    drug_name      Time  Result
0    15-10-2020  Temperature      diltiazem hydrochloride        ID     1.0
1    15-10-2020     Pressure      diltiazem hydrochloride        ID     2.0
2    16-10-2020  Temperature          docetaxel injection        ID     3.0
3    16-10-2020     Pressure          docetaxel injection        ID     4.0
4    17-10-2020  Temperature     erythrocin™ lactobionate        ID     5.0
..          ...          ...                          ...       ...     ...
255  22-10-2020     Pressure         butorphanol tartrate  12:30:00    28.0
256  23-10-2020  Temperature  buprenorphine hydrochloride  12:30:00    24.0
257  23-10-2020     Pressure  buprenorphine hydrochloride  12:30:00    15.0
258  24-10-2020  Temperature                    skelaxin®  12:30:00    13.0
259  24-10-2020     Pressure                    skelaxin®  12:30:00    20.0

[260 rows x 5 columns]

# Pivot

In [23]:
melting_data.pivot(
    index=["Date", 'drug_name', 'Parameter'],
    columns="Time",
    values="Result"
)

Time                                                10:30:00  11:30:00  \
Date       drug_name                   Parameter
15-10-2020 diltiazem hydrochloride     Pressure         18.0      19.0
                                       Temperature      20.0      20.0
16-10-2020 docetaxel injection         Pressure         26.0      29.0
                                       Temperature      23.0      25.0
17-10-2020 erythrocin™ lactobionate    Pressure          9.0       9.0
                                       Temperature      22.0      21.0
18-10-2020 fentanyl citrate            Pressure         24.0       NaN
                                       Temperature      40.0       NaN
19-10-2020 gentamicin sulfate          Pressure         28.0      29.0
                                       Temperature      56.0      57.0
20-10-2020 ketamine hydrochloride      Pressure         16.0      17.0
                                       Temperature      13.0      14.0
21-10-2020 ammonium chloride           Pressure         11.0      13.0
                                       Temperature      14.0      11.0
22-10-2020 butorphanol tartrate        Pressure         28.0      29.0
                                       Temperature      21.0      22.0
23-10-2020 buprenorphine hydrochloride Pressure         13.0      14.0
                                       Temperature      22.0      23.0
24-10-2020 skelaxin®                   Pressure         18.0      19.0
                                       Temperature      12.0      13.0

Time                                                12:30:00  1:30:00  \
Date       drug_name                   Parameter
15-10-2020 diltiazem hydrochloride     Pressure         20.0     12.0
                                       Temperature      21.0     23.0
16-10-2020 docetaxel injection         Pressure         28.0      NaN
                                       Temperature      25.0      NaN
17-10-2020 erythrocin™ lactobionate    Pressure         11.0      8.0
                                       Temperature      20.0     24.0
18-10-2020 fentanyl citrate            Pressure         27.0     18.0
                                       Temperature      42.0     34.0
19-10-2020 gentamicin sulfate          Pressure         30.0     23.0
                                       Temperature      58.0     46.0
20-10-2020 ketamine hydrochloride      Pressure         18.0     12.0
                                       Temperature      15.0      8.0
21-10-2020 ammonium chloride           Pressure         14.0      3.0
                                       Temperature      10.0     20.0
22-10-2020 butorphanol tartrate        Pressure         28.0     20.0
                                       Temperature      23.0     12.0
23-10-2020 buprenorphine hydrochloride Pressure         15.0      8.0
                                       Temperature      24.0     13.0
24-10-2020 skelaxin®                   Pressure         20.0     12.0
                                       Temperature      13.0     13.0

Time                                                2:30:00  3:30:00  4:30:00  \
Date       drug_name                   Parameter
15-10-2020 diltiazem hydrochloride     Pressure        13.0      NaN     11.0
                                       Temperature     22.0      NaN     21.0
16-10-2020 docetaxel injection         Pressure        22.0     22.0      NaN
                                       Temperature     17.0     18.0      NaN
17-10-2020 erythrocin™ lactobionate    Pressure         NaN      NaN      7.0
                                       Temperature      NaN      NaN     27.0
18-10-2020 fentanyl citrate            Pressure        19.0     20.0     21.0
                                       Temperature     35.0     36.0     36.0
19-10-2020 gentamicin sulfate          Pressure        24.0      NaN     25.0
                                       Temperature     47.0      NaN     48.0
20-10-2020 ketamine hydrochloride      Pressure        12.0     13.0      NaN
                                       Temperature      9.0     10.0      NaN
21-10-2020 ammonium chloride           Pressure         4.0      4.0      4.0
                                       Temperature     19.0     19.0     18.0
22-10-2020 butorphanol tartrate        Pressure        22.0     22.0     22.0
                                       Temperature     13.0     14.0     15.0
23-10-2020 buprenorphine hydrochloride Pressure         9.0     10.0     11.0
                                       Temperature     14.0     15.0     16.0
24-10-2020 skelaxin®                   Pressure        11.0     11.0     11.0
                                       Temperature     13.0     13.0     13.0

Time                                                5:30:00  6:30:00  7:30:00  \
Date       drug_name                   Parameter
15-10-2020 diltiazem hydrochloride     Pressure        13.0     14.0     16.0
                                       Temperature     21.0     22.0     23.0
16-10-2020 docetaxel injection         Pressure        22.0     23.0      NaN
                                       Temperature     17.0     18.0      NaN
17-10-2020 erythrocin™ lactobionate    Pressure         NaN      9.0     10.0
                                       Temperature      NaN     26.0     25.0
18-10-2020 fentanyl citrate            Pressure        22.0     23.0     24.0
                                       Temperature     37.0     38.0     37.0
19-10-2020 gentamicin sulfate          Pressure        26.0     27.0     28.0
                                       Temperature     48.0     49.0     50.0
20-10-2020 ketamine hydrochloride      Pressure        15.0     15.0     15.0
                                       Temperature     11.0     12.0     12.0
21-10-2020 ammonium chloride           Pressure         6.0      8.0      9.0
                                       Temperature     17.0     16.0     15.0
22-10-2020 butorphanol tartrate        Pressure        22.0     23.0     25.0
                                       Temperature     16.0     17.0     18.0
23-10-2020 buprenorphine hydrochloride Pressure        11.0     12.0     12.0
                                       Temperature     17.0     18.0     19.0
24-10-2020 skelaxin®                   Pressure        13.0     14.0     16.0
                                       Temperature     13.0     14.0     13.0

Time                                                8:30:00  9:30:00    ID
Date       drug_name                   Parameter
15-10-2020 diltiazem hydrochloride     Pressure        16.0     24.0   2.0
                                       Temperature     21.0     22.0   1.0
16-10-2020 docetaxel injection         Pressure         NaN     27.0   4.0
                                       Temperature      NaN     23.0   3.0
17-10-2020 erythrocin™ lactobionate    Pressure        11.0     10.0   6.0
                                       Temperature     24.0     23.0   5.0
18-10-2020 fentanyl citrate            Pressure        25.0     25.0   8.0
                                       Temperature     38.0     39.0   7.0
19-10-2020 gentamicin sulfate          Pressure        29.0     28.0  10.0
                                       Temperature     52.0     55.0   9.0
20-10-2020 ketamine hydrochloride      Pressure        15.0      NaN  12.0
                                       Temperature     11.0      NaN  11.0
21-10-2020 ammonium chloride           Pressure         NaN      9.0  14.0
                                       Temperature      NaN     13.0  13.0
22-10-2020 butorphanol tartrate        Pressure        26.0     27.0  16.0
                                       Temperature     19.0     20.0  15.0
23-10-2020 buprenorphine hydrochloride Pressure        11.0     12.0  18.0
                                       Temperature     20.0     21.0  17.0
24-10-2020 skelaxin®                   Pressure        16.0     17.0  20.0
                                       Temperature     14.0     13.0  19.0

In [2]:
df1 = pd.DataFrame({'name':["Ram","Shyam","Mukesh","Suresh"],'age':[10,18,60,50]})
df1

     name  age
0     Ram   10
1   Shyam   18
2  Mukesh   60
3  Suresh   50

In [33]:
def calc_age(x):
    if (np.any(x['age'] < 18)):
        x['age'] = 'kid';
    elif (np.any(x['age'] >= 18) & np.any(x['age'] <= 50)):
        x['age'] = 'adult'
    elif (np.any(x['age'] > 50)):
        x['age'] = 'senior';
    return x;

df1.groupby('name').apply(calc_age)

     name     age
0     Ram     kid
1   Shyam   adult
2  Mukesh  senior
3  Suresh   adult

In [12]:
temp_bins = [1, 17, 51, 100];
temp_labels = ['kid', 'adult', 'senior']
pd.cut(df1['age'],
      bins=temp_bins,
      labels=temp_labels)

0       kid
1     adult
2    senior
3     adult
Name: age, dtype: category
Categories (3, object): ['kid' < 'adult' < 'senior']